all:
  vars:
    ansible_connection: ssh
    ansible_ssh_user: centos
    ansible_become: True
zookeeper:
  hosts:
    ec2-54-213-175-189.us-west-2.compute.amazonaws.com:
    ec2-34-217-17-78.us-west-2.compute.amazonaws.com:
    ec2-34-210-68-62.us-west-2.compute.amazonaws.com:
broker:
  hosts:
    ec2-34-210-84-57.us-west-2.compute.amazonaws.com:
    ec2-54-186-213-68.us-west-2.compute.amazonaws.com:
    ec2-35-167-11-234.us-west-2.compute.amazonaws.com:
connect:
  hosts:
    ec2-54-213-205-238.us-west-2.compute.amazonaws.com:
    ec2-54-71-122-103.us-west-2.compute.amazonaws.com:
schemaregistry:
  hosts:
    ec2-54-245-165-138.us-west-2.compute.amazonaws.com:
    ec2-52-37-214-190.us-west-2.compute.amazonaws.com:
