kafka:
  rest:
    user: kafka-rest
    group: kafka-rest
    heap: -Xmx1000M
    logdir: /var/log/kafka-rest
  broker:
    user: kafka
    group: kafka
    config_file: /etc/kafka/server.properties
    logging_config_file: /etc/kafka/server.logging.properties
    systemd_file: /usr/lib/systemd/system/kafka.service
    service_name: kafka
    datadir:
      - /var/lib/kafka
    environment:
      KAFKA_HEAP_OPTS: "-Xmx1000M"
      LOG_DIR: /var/log/kafka
    systemd:
      enabled: yes
      state: started
      LimitNOFILE: 128000
      TimeoutStopSec: 300
      RestartSec: 5
    config:
      confluent.support.customer.id: anonymous
      confluent.support.metrics.enable: true
      group.initial.rebalance.delay.ms: 0
      log.retention.check.interval.ms: 300000
      log.retention.hours: 168
      log.segment.bytes: 1073741824
      num.io.threads: 16
      num.network.threads: 8
      num.partitions: 1
      num.recovery.threads.per.data.dir: 2
      offsets.topic.replication.factor: 3
      socket.receive.buffer.bytes: 102400
      socket.request.max.bytes: 104857600
      socket.send.buffer.bytes: 102400
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
      zookeeper.connection.timeout.ms: 6000
      metric.reporters: io.confluent.metrics.reporter.ConfluentMetricsReporter
      confluent.metrics.reporter.bootstrap.servers: "{{inventory_hostname}}:9092"
  connect:
    distributed:
      user: connect-distributed
      group: connect-distributed
      heap: -Xmx1000M
    standalone:
      user: connect-standalone
      group: connect-standalone
      heap: -Xmx1000M
zookeeper:
  user: zookeeper
  group: zookeeper
  config_file: /etc/kafka/zookeeper.properties
  logging_config_file: /etc/kafka/zookeeper.logging.properties
  systemd_file: /usr/lib/systemd/system/zookeeper.service
  service_name: zookeeper
  config:
    clientPort: 2181
    maxClientCnxns: 0
    initLimit: 5
    syncLimit: 2
    autopurge.snapRetainCount: 10
    autopurge.purgeInterval: 1
    dataDir: /var/lib/zookeeper
  environment:
    KAFKA_HEAP_OPTS: "-Xmx1000M"
    LOG_DIR: /var/log/zookeeper
  systemd:
    enabled: yes
    state: started
    LimitNOFILE: 128000
    TimeoutStopSec: 300
    RestartSec: 5
schema:
  registry:
    user: schema-registry
    group: schema-registry
    config_file: /etc/kafka/schema-registry.properties
    logging_config_file: /etc/kafka/schema-registry.logging.properties
    systemd_file: /usr/lib/systemd/system/schema-registry.service
    service_name: schema-registry
    config:
      listeners: http://0.0.0.0:8081
      kafkastore.topic: _schemas
      debug: false
    environment:
      SCHEMA_REGISTRY_HEAP_OPTS: "-Xmx1000M"
      LOG_DIR: /var/log/schema-registry
    systemd:
      enabled: yes
      state: started
      LimitNOFILE: 128000
      TimeoutStopSec: 300
      RestartSec: 5
confluent:
  package_name: confluent-platform-2.11
  repository:
    debian:
    redhat:
      main:
        baseurl: https://packages.confluent.io/rpm/4.0
        gpgcheck: 1
        gpgkey: https://packages.confluent.io/rpm/4.0/archive.key
        enabled: 1
      dist:
        baseurl: https://packages.confluent.io/rpm/4.0/7
        gpgcheck: 1
        gpgkey:  https://packages.confluent.io/rpm/4.0/archive.key
        enabled: 1
  control:
    center:
      user: control-center
      group: control-center
      heap: -Xmx1000M
      datadir: /var/lib/control-center
      logdir: /var/log/control-center