- import_role:
    name: common
- name: control center create group
  group:
    name: "{{confluent.control.center.group}}"
- name: control center create user
  user:
    name: "{{confluent.control.center.user}}"
    comment: "Control Center User"
    system: yes
    group: "{{confluent.control.center.group}}"
- name: control center create log dir
  file:
    path: "{{confluent.control.center.environment.LOG_DIR}}"
    state: directory
    mode: 0555
    owner: "{{confluent.control.center.user}}"
    group: "{{confluent.control.center.group}}"
- name: control center create data dir
  file:
    path: "{{confluent.control.center.data_dir}}"
    state: directory
    mode: 0550
    owner: "{{confluent.control.center.user}}"
    group: "{{confluent.control.center.group}}"
- name: control center create temp dir
  file:
    path: "{{confluent.control.center.tmp_dir}}"
    state: directory
    mode: 0700
    owner: "{{confluent.control.center.user}}"
    group: "{{confluent.control.center.group}}"
- name: control center create systemd unit
  template:
    src: control-center.service.j2
    dest: "{{confluent.control.center.systemd_file}}"
  notify:
    - reload systemd
    - restart control center
- name: control center create config
  template:
    src: control-center.properties.j2
    dest: "{{confluent.control.center.config_file}}"
  notify:
    - restart control center
- name: control center configure service
  systemd:
    name: "{{confluent.control.center.service_name}}"
    enabled: "{{confluent.control.center.systemd.enabled}}"
    state: "{{confluent.control.center.systemd.state}}"
